@currentDate = {{$datetime 'yyyy-MM-dd'}}
@baseUrl=http://localhost:7264

POST {{baseUrl}}/api/rfid HTTP/1.1
Accept: application/json

{
    "id": "{{$guid}}",
    "validFrom": "{{currentDate}}"
}

###
GET {{baseUrl}}/api/rfid/490efc44-7e83-4d99-9516-d1d1a88321f0 HTTP/1.1
Accept: application/json
